# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2057f6a5fd1ab340cca83d311ebc2d8b31f5a1730fd695d954317685c2403ba905a39b1f25e90f14cd2b44286eba1e191697d8fd4095bbe9b765648d6a6001c1

test:
  secret_key_base: 7667cba7fcbca2ccae1b819618f688c9b9196dec0ba0496b06579896db490e3fab3d225110c474c284119b48bc1725a46bb0c1eec8d6f912390ac048ddeab947

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
